version: '3.6'

services: 
  admin-service:
    build: .
    container_name: admin-service
    ports:
      - "3000:3000"
    volumes:
      - ./app/config.json:/app/config.json
      - ./mypipe:/mypipe
    environment:
      - PASSWORD=heya
    restart: always